# Generated by Django 6.0.6 on 2026-07-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Site content',
                'verbose_name_plural': 'Site content',
            },
        ),
    ]
