[control_plane]
control-plane ansible_host=54.146.185.155 private_ip=172.31.85.66

[workers]
worker-1 ansible_host=3.84.94.182 private_ip=172.31.81.141
worker-2 ansible_host=44.211.142.76 private_ip=172.31.89.137
worker-3 ansible_host=3.92.190.198 private_ip=172.31.80.253

[k8s_nodes:children]
control_plane
workers

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file={{ inventory_dir }}/labsuser.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'